import Link from "next/link";
import { ArrowRight, ChevronRight, PenLine, Sparkles } from "lucide-react";
import type { Metadata } from "next";
import { getAuthUser } from "@/lib/auth";
import { SiteHeader } from "@/components/marketing/site-header";
import { Button } from "@/components/ui/button";
import { supabaseAdmin } from "@/lib/supabase/server";
import { getSiteUrl } from "@/lib/site";

export const revalidate = 3600;

const PAGE_TITLE = "AI Writing Examples — Citeplex";
const PAGE_DESCRIPTION =
  "See real articles written by Citeplex's AI Article Writer for brands like Ahrefs, SurferSEO, Semrush, and Writesonic. SEO-optimized, brand-voice matched, fully automated.";

export const metadata: Metadata = {
  title: PAGE_TITLE,
  description: PAGE_DESCRIPTION,
  alternates: { canonical: `${getSiteUrl()}/examples` },
  openGraph: {
    title: PAGE_TITLE,
    description: PAGE_DESCRIPTION,
    url: `${getSiteUrl()}/examples`,
    type: "website",
  },
};

const FAQ_ITEMS = [
  {
    question: "How does Citeplex write articles?",
    answer:
      "Citeplex uses Claude Opus 4.6 — one of the most advanced AI models — combined with Ahrefs keyword data, SERP analysis, and your brand voice profile. The AI researches the topic, creates a detailed outline, writes the full article with expert quotes, statistics, and citations, then generates AI images and embeds relevant YouTube videos. Every article includes FAQ schema, key takeaways, and internal linking.",
  },
  {
    question: "What makes these articles SEO-optimized?",
    answer:
      "Each article starts with Ahrefs keyword research — volume, difficulty, traffic potential, and parent topic analysis. The AI optimizes heading structure (H1-H3), keyword density, meta descriptions, internal/external links, image alt text, and FAQ JSON-LD schema. Articles are fact-checked and coherence-verified before publishing.",
  },
  {
    question: "Can Citeplex match my brand voice?",
    answer:
      "Yes. During onboarding, Citeplex analyzes your existing content to learn your writing style — tone, vocabulary, sentence structure, and personality. Every article is written to match your unique brand voice, so it sounds like you, not a generic AI. These examples demonstrate how the AI adapts to different brand styles.",
  },
  {
    question: "Which AI model writes the articles?",
    answer:
      "Citeplex uses a multi-model pipeline: Claude Opus 4.6 for research, outlining, and main article writing (the 'strong' chain), and Claude Sonnet 4.6 for fact-checking, coherence verification, and internal link optimization (the 'fast' chain). DALL-E 3 generates custom cover images and inline illustrations.",
  },
  {
    question: "How long does it take to generate an article?",
    answer:
      "A full article — including keyword research, topic research, outline generation, 1500+ word article writing, AI image generation, YouTube video embedding, and quality checks — takes approximately 3-5 minutes. Citeplex can generate and publish articles daily on autopilot.",
  },
  {
    question: "Are these real articles or demos?",
    answer:
      "These are real articles generated by Citeplex's production AI pipeline — the same system that writes articles for paying customers. Nothing was hand-edited. They demonstrate the actual output quality, formatting, and SEO optimization you get with Citeplex.",
  },
];

async function getExamples() {
  const { data } = await supabaseAdmin
    .from("writing_examples")
    .select("slug, brand_name, brand_url, title, keyword, meta_description, cover_image_url, word_count, created_at")
    .order("created_at", { ascending: true });
  return data ?? [];
}

export default async function ExamplesPage() {
  const user = await getAuthUser();
  const examples = await getExamples();

  return (
    <div className="min-h-screen bg-background overflow-hidden pt-16">
      <SiteHeader authenticated={!!user} />

      {/* Hero */}
      <section className="relative">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-primary/12 via-transparent to-transparent" />
        <div className="pointer-events-none absolute top-24 left-1/4 h-72 w-72 rounded-full bg-primary/8 blur-3xl" />
        <div className="pointer-events-none absolute top-40 right-1/4 h-64 w-64 rounded-full bg-indigo-500/8 blur-3xl" />

        <div className="relative mx-auto max-w-6xl px-4 pb-6 pt-10 sm:px-6 sm:pt-14">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary">
              <PenLine className="h-4 w-4" />
              AI-Powered Content
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">
              Writing{" "}
              <span className="bg-linear-to-r from-primary via-blue-500 to-indigo-500 bg-clip-text text-transparent">
                Examples
              </span>
            </h1>
            <p className="mx-auto mt-5 max-w-xl text-lg text-muted-foreground sm:text-xl">
              Real articles written by Citeplex&apos;s AI — for real brands.
              No hand-editing, no cherry-picking. This is what you get.
            </p>
          </div>
        </div>
      </section>

      {/* Examples Grid */}
      <section className="relative">
        <div className="mx-auto max-w-6xl px-4 pb-20 sm:px-6">
          {examples.length > 0 ? (
            <ul className="mt-10 grid gap-6 sm:grid-cols-2 lg:gap-8">
              {examples.map((ex) => (
                <li key={ex.slug}>
                  <article className="group h-full">
                    <Link
                      href={`/examples/${ex.slug}`}
                      className="flex h-full flex-col overflow-hidden rounded-2xl border border-border/80 bg-card shadow-sm transition-all duration-300 hover:border-primary/25 hover:shadow-lg hover:shadow-primary/5"
                    >
                      <div className="relative aspect-2/1 w-full overflow-hidden bg-muted">
                        {ex.cover_image_url ? (
                          /* eslint-disable-next-line @next/next/no-img-element */
                          <img
                            src={ex.cover_image_url}
                            alt={ex.title}
                            className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"
                          />
                        ) : (
                          <div className="flex h-full w-full items-center justify-center bg-linear-to-br from-primary/10 via-muted to-indigo-500/10">
                            <PenLine className="h-12 w-12 text-primary/20" />
                          </div>
                        )}
                        <div className="absolute inset-0 bg-linear-to-t from-background/80 via-transparent to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
                      </div>
                      <div className="flex flex-1 flex-col p-6 sm:p-7">
                        <div className="mb-3 inline-flex items-center gap-1.5 self-start rounded-full border border-primary/15 bg-primary/5 px-3 py-1 text-xs font-medium text-primary">
                          <PenLine className="h-3 w-3" />
                          Written for {ex.brand_name}
                        </div>
                        <h2 className="text-xl font-bold leading-snug tracking-tight transition-colors group-hover:text-primary sm:text-2xl">
                          {ex.title}
                        </h2>
                        {ex.meta_description && (
                          <p className="mt-3 line-clamp-3 flex-1 text-[15px] leading-relaxed text-muted-foreground">
                            {ex.meta_description}
                          </p>
                        )}
                        <div className="mt-5 flex items-center justify-between">
                          <span className="inline-flex items-center gap-1 text-sm font-semibold text-primary">
                            Read full article
                            <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
                          </span>
                          <span className="text-xs text-muted-foreground">
                            {ex.word_count > 0 && `${ex.word_count.toLocaleString()} words · `}AI Generated
                          </span>
                        </div>
                      </div>
                    </Link>
                  </article>
                </li>
              ))}
            </ul>
          ) : (
            <div className="mx-auto mt-16 max-w-lg">
              <div className="relative overflow-hidden rounded-2xl border border-dashed border-primary/25 bg-linear-to-br from-card via-card to-primary/4 p-10 text-center shadow-sm">
                <div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                  <PenLine className="h-7 w-7" />
                </div>
                <h2 className="text-xl font-bold tracking-tight">
                  Examples coming soon
                </h2>
                <p className="mt-3 text-[15px] leading-relaxed text-muted-foreground">
                  Our AI is generating showcase articles for top SEO brands.
                  Check back shortly to see the results.
                </p>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* FAQ */}
      <section className="border-t bg-muted/30">
        <div className="mx-auto max-w-3xl px-4 py-24 sm:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-sm font-semibold uppercase tracking-wider text-primary">
              FAQ
            </p>
            <h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">
              How Citeplex writes articles
            </h2>
            <p className="mt-4 text-muted-foreground">
              Everything you need to know about our AI article writing pipeline.
            </p>
          </div>

          <div className="mt-14 space-y-4">
            {FAQ_ITEMS.map((faq) => (
              <details key={faq.question} className="group rounded-xl border bg-card">
                <summary className="flex cursor-pointer items-center justify-between p-5 font-semibold transition-colors hover:text-primary [&::-webkit-details-marker]:hidden">
                  {faq.question}
                  <ChevronRight className="h-4 w-4 shrink-0 text-muted-foreground transition-transform group-open:rotate-90" />
                </summary>
                <div className="px-5 pb-5 text-sm leading-relaxed text-muted-foreground">
                  {faq.answer}
                </div>
              </details>
            ))}
          </div>
        </div>

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: FAQ_ITEMS.map((faq) => ({
                "@type": "Question",
                name: faq.question,
                acceptedAnswer: {
                  "@type": "Answer",
                  text: faq.answer,
                },
              })),
            }),
          }}
        />
      </section>

      {/* CTA */}
      <section className="border-t">
        <div className="mx-auto max-w-6xl px-4 py-24 sm:px-6">
          <div className="relative mx-auto max-w-3xl overflow-hidden rounded-3xl border bg-card p-10 text-center shadow-xl sm:p-16">
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,var(--tw-gradient-stops))] from-primary/5 via-transparent to-transparent" />
            <div className="relative">
              <Sparkles className="mx-auto h-10 w-10 text-primary" />
              <h2 className="mt-6 text-3xl font-extrabold tracking-tight sm:text-4xl">
                Want articles like these for your brand?
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-lg text-muted-foreground">
                Citeplex writes SEO-optimized articles with your brand voice,
                AI images, keyword research, and automatic publishing — every day, on autopilot.
              </p>
              <Button
                size="lg"
                className="mt-8 h-13 rounded-xl px-10 text-base font-semibold shadow-lg shadow-primary/25"
                asChild
              >
                <Link href="/login">
                  Start Your Free Trial
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* ItemList JSON-LD */}
      {examples.length > 0 && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ItemList",
              name: "Citeplex AI Writing Examples",
              description: PAGE_DESCRIPTION,
              numberOfItems: examples.length,
              itemListElement: examples.map((ex, i) => ({
                "@type": "ListItem",
                position: i + 1,
                url: `${getSiteUrl()}/examples/${ex.slug}`,
                name: ex.title,
              })),
            }),
          }}
        />
      )}
    </div>
  );
}
