export interface Country {
  code: string;
  name: string;
  nativeName: string;
  lang: string;
  langName: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", nativeName: "افغانستان", lang: "ps", langName: "Pashto" },
  { code: "AL", name: "Albania", nativeName: "Shqipëria", lang: "sq", langName: "Albanian" },
  { code: "DZ", name: "Algeria", nativeName: "الجزائر", lang: "ar", langName: "Arabic" },
  { code: "AD", name: "Andorra", nativeName: "Andorra", lang: "ca", langName: "Catalan" },
  { code: "AO", name: "Angola", nativeName: "Angola", lang: "pt", langName: "Portuguese" },
  { code: "AG", name: "Antigua and Barbuda", nativeName: "Antigua and Barbuda", lang: "en", langName: "English" },
  { code: "AR", name: "Argentina", nativeName: "Argentina", lang: "es", langName: "Spanish" },
  { code: "AM", name: "Armenia", nativeName: "Հայաստան", lang: "hy", langName: "Armenian" },
  { code: "AU", name: "Australia", nativeName: "Australia", lang: "en", langName: "English" },
  { code: "AT", name: "Austria", nativeName: "Österreich", lang: "de", langName: "German" },
  { code: "AZ", name: "Azerbaijan", nativeName: "Azərbaycan", lang: "az", langName: "Azerbaijani" },
  { code: "BS", name: "Bahamas", nativeName: "Bahamas", lang: "en", langName: "English" },
  { code: "BH", name: "Bahrain", nativeName: "البحرين", lang: "ar", langName: "Arabic" },
  { code: "BD", name: "Bangladesh", nativeName: "বাংলাদেশ", lang: "bn", langName: "Bengali" },
  { code: "BB", name: "Barbados", nativeName: "Barbados", lang: "en", langName: "English" },
  { code: "BY", name: "Belarus", nativeName: "Беларусь", lang: "be", langName: "Belarusian" },
  { code: "BE", name: "Belgium", nativeName: "België", lang: "nl", langName: "Dutch" },
  { code: "BZ", name: "Belize", nativeName: "Belize", lang: "en", langName: "English" },
  { code: "BJ", name: "Benin", nativeName: "Bénin", lang: "fr", langName: "French" },
  { code: "BT", name: "Bhutan", nativeName: "འབྲུག", lang: "dz", langName: "Dzongkha" },
  { code: "BO", name: "Bolivia", nativeName: "Bolivia", lang: "es", langName: "Spanish" },
  { code: "BA", name: "Bosnia and Herzegovina", nativeName: "Bosna i Hercegovina", lang: "bs", langName: "Bosnian" },
  { code: "BW", name: "Botswana", nativeName: "Botswana", lang: "en", langName: "English" },
  { code: "BR", name: "Brazil", nativeName: "Brasil", lang: "pt", langName: "Portuguese" },
  { code: "BN", name: "Brunei", nativeName: "Brunei", lang: "ms", langName: "Malay" },
  { code: "BG", name: "Bulgaria", nativeName: "България", lang: "bg", langName: "Bulgarian" },
  { code: "BF", name: "Burkina Faso", nativeName: "Burkina Faso", lang: "fr", langName: "French" },
  { code: "BI", name: "Burundi", nativeName: "Burundi", lang: "fr", langName: "French" },
  { code: "CV", name: "Cabo Verde", nativeName: "Cabo Verde", lang: "pt", langName: "Portuguese" },
  { code: "KH", name: "Cambodia", nativeName: "កម្ពុជា", lang: "km", langName: "Khmer" },
  { code: "CM", name: "Cameroon", nativeName: "Cameroun", lang: "fr", langName: "French" },
  { code: "CA", name: "Canada", nativeName: "Canada", lang: "en", langName: "English" },
  { code: "CF", name: "Central African Republic", nativeName: "République centrafricaine", lang: "fr", langName: "French" },
  { code: "TD", name: "Chad", nativeName: "Tchad", lang: "fr", langName: "French" },
  { code: "CL", name: "Chile", nativeName: "Chile", lang: "es", langName: "Spanish" },
  { code: "CN", name: "China", nativeName: "中国", lang: "zh", langName: "Chinese" },
  { code: "CO", name: "Colombia", nativeName: "Colombia", lang: "es", langName: "Spanish" },
  { code: "KM", name: "Comoros", nativeName: "Comores", lang: "fr", langName: "French" },
  { code: "CG", name: "Congo", nativeName: "Congo", lang: "fr", langName: "French" },
  { code: "CD", name: "Congo (DRC)", nativeName: "Congo (RDC)", lang: "fr", langName: "French" },
  { code: "CR", name: "Costa Rica", nativeName: "Costa Rica", lang: "es", langName: "Spanish" },
  { code: "CI", name: "Côte d'Ivoire", nativeName: "Côte d'Ivoire", lang: "fr", langName: "French" },
  { code: "HR", name: "Croatia", nativeName: "Hrvatska", lang: "hr", langName: "Croatian" },
  { code: "CU", name: "Cuba", nativeName: "Cuba", lang: "es", langName: "Spanish" },
  { code: "CY", name: "Cyprus", nativeName: "Κύπρος", lang: "el", langName: "Greek" },
  { code: "CZ", name: "Czechia", nativeName: "Česko", lang: "cs", langName: "Czech" },
  { code: "DK", name: "Denmark", nativeName: "Danmark", lang: "da", langName: "Danish" },
  { code: "DJ", name: "Djibouti", nativeName: "Djibouti", lang: "fr", langName: "French" },
  { code: "DM", name: "Dominica", nativeName: "Dominica", lang: "en", langName: "English" },
  { code: "DO", name: "Dominican Republic", nativeName: "República Dominicana", lang: "es", langName: "Spanish" },
  { code: "EC", name: "Ecuador", nativeName: "Ecuador", lang: "es", langName: "Spanish" },
  { code: "EG", name: "Egypt", nativeName: "مصر", lang: "ar", langName: "Arabic" },
  { code: "SV", name: "El Salvador", nativeName: "El Salvador", lang: "es", langName: "Spanish" },
  { code: "GQ", name: "Equatorial Guinea", nativeName: "Guinea Ecuatorial", lang: "es", langName: "Spanish" },
  { code: "ER", name: "Eritrea", nativeName: "ኤርትራ", lang: "ti", langName: "Tigrinya" },
  { code: "EE", name: "Estonia", nativeName: "Eesti", lang: "et", langName: "Estonian" },
  { code: "SZ", name: "Eswatini", nativeName: "Eswatini", lang: "en", langName: "English" },
  { code: "ET", name: "Ethiopia", nativeName: "ኢትዮጵያ", lang: "am", langName: "Amharic" },
  { code: "FJ", name: "Fiji", nativeName: "Fiji", lang: "en", langName: "English" },
  { code: "FI", name: "Finland", nativeName: "Suomi", lang: "fi", langName: "Finnish" },
  { code: "FR", name: "France", nativeName: "France", lang: "fr", langName: "French" },
  { code: "GA", name: "Gabon", nativeName: "Gabon", lang: "fr", langName: "French" },
  { code: "GM", name: "Gambia", nativeName: "Gambia", lang: "en", langName: "English" },
  { code: "GE", name: "Georgia", nativeName: "საქართველო", lang: "ka", langName: "Georgian" },
  { code: "DE", name: "Germany", nativeName: "Deutschland", lang: "de", langName: "German" },
  { code: "GH", name: "Ghana", nativeName: "Ghana", lang: "en", langName: "English" },
  { code: "GR", name: "Greece", nativeName: "Ελλάδα", lang: "el", langName: "Greek" },
  { code: "GD", name: "Grenada", nativeName: "Grenada", lang: "en", langName: "English" },
  { code: "GT", name: "Guatemala", nativeName: "Guatemala", lang: "es", langName: "Spanish" },
  { code: "GN", name: "Guinea", nativeName: "Guinée", lang: "fr", langName: "French" },
  { code: "GW", name: "Guinea-Bissau", nativeName: "Guiné-Bissau", lang: "pt", langName: "Portuguese" },
  { code: "GY", name: "Guyana", nativeName: "Guyana", lang: "en", langName: "English" },
  { code: "HT", name: "Haiti", nativeName: "Haïti", lang: "fr", langName: "French" },
  { code: "HN", name: "Honduras", nativeName: "Honduras", lang: "es", langName: "Spanish" },
  { code: "HU", name: "Hungary", nativeName: "Magyarország", lang: "hu", langName: "Hungarian" },
  { code: "IS", name: "Iceland", nativeName: "Ísland", lang: "is", langName: "Icelandic" },
  { code: "IN", name: "India", nativeName: "India", lang: "en", langName: "English" },
  { code: "ID", name: "Indonesia", nativeName: "Indonesia", lang: "id", langName: "Indonesian" },
  { code: "IR", name: "Iran", nativeName: "ایران", lang: "fa", langName: "Persian" },
  { code: "IQ", name: "Iraq", nativeName: "العراق", lang: "ar", langName: "Arabic" },
  { code: "IE", name: "Ireland", nativeName: "Ireland", lang: "en", langName: "English" },
  { code: "IL", name: "Israel", nativeName: "ישראל", lang: "he", langName: "Hebrew" },
  { code: "IT", name: "Italy", nativeName: "Italia", lang: "it", langName: "Italian" },
  { code: "JM", name: "Jamaica", nativeName: "Jamaica", lang: "en", langName: "English" },
  { code: "JP", name: "Japan", nativeName: "日本", lang: "ja", langName: "Japanese" },
  { code: "JO", name: "Jordan", nativeName: "الأردن", lang: "ar", langName: "Arabic" },
  { code: "KZ", name: "Kazakhstan", nativeName: "Қазақстан", lang: "kk", langName: "Kazakh" },
  { code: "KE", name: "Kenya", nativeName: "Kenya", lang: "en", langName: "English" },
  { code: "KI", name: "Kiribati", nativeName: "Kiribati", lang: "en", langName: "English" },
  { code: "KP", name: "North Korea", nativeName: "조선", lang: "ko", langName: "Korean" },
  { code: "KR", name: "South Korea", nativeName: "대한민국", lang: "ko", langName: "Korean" },
  { code: "KW", name: "Kuwait", nativeName: "الكويت", lang: "ar", langName: "Arabic" },
  { code: "KG", name: "Kyrgyzstan", nativeName: "Кыргызстан", lang: "ky", langName: "Kyrgyz" },
  { code: "LA", name: "Laos", nativeName: "ລາວ", lang: "lo", langName: "Lao" },
  { code: "LV", name: "Latvia", nativeName: "Latvija", lang: "lv", langName: "Latvian" },
  { code: "LB", name: "Lebanon", nativeName: "لبنان", lang: "ar", langName: "Arabic" },
  { code: "LS", name: "Lesotho", nativeName: "Lesotho", lang: "en", langName: "English" },
  { code: "LR", name: "Liberia", nativeName: "Liberia", lang: "en", langName: "English" },
  { code: "LY", name: "Libya", nativeName: "ليبيا", lang: "ar", langName: "Arabic" },
  { code: "LI", name: "Liechtenstein", nativeName: "Liechtenstein", lang: "de", langName: "German" },
  { code: "LT", name: "Lithuania", nativeName: "Lietuva", lang: "lt", langName: "Lithuanian" },
  { code: "LU", name: "Luxembourg", nativeName: "Luxembourg", lang: "fr", langName: "French" },
  { code: "MG", name: "Madagascar", nativeName: "Madagasikara", lang: "fr", langName: "French" },
  { code: "MW", name: "Malawi", nativeName: "Malawi", lang: "en", langName: "English" },
  { code: "MY", name: "Malaysia", nativeName: "Malaysia", lang: "ms", langName: "Malay" },
  { code: "MV", name: "Maldives", nativeName: "ދިވެހިރާއްޖެ", lang: "dv", langName: "Dhivehi" },
  { code: "ML", name: "Mali", nativeName: "Mali", lang: "fr", langName: "French" },
  { code: "MT", name: "Malta", nativeName: "Malta", lang: "mt", langName: "Maltese" },
  { code: "MH", name: "Marshall Islands", nativeName: "Marshall Islands", lang: "en", langName: "English" },
  { code: "MR", name: "Mauritania", nativeName: "موريتانيا", lang: "ar", langName: "Arabic" },
  { code: "MU", name: "Mauritius", nativeName: "Mauritius", lang: "en", langName: "English" },
  { code: "MX", name: "Mexico", nativeName: "México", lang: "es", langName: "Spanish" },
  { code: "FM", name: "Micronesia", nativeName: "Micronesia", lang: "en", langName: "English" },
  { code: "MD", name: "Moldova", nativeName: "Moldova", lang: "ro", langName: "Romanian" },
  { code: "MC", name: "Monaco", nativeName: "Monaco", lang: "fr", langName: "French" },
  { code: "MN", name: "Mongolia", nativeName: "Монгол", lang: "mn", langName: "Mongolian" },
  { code: "ME", name: "Montenegro", nativeName: "Crna Gora", lang: "sr", langName: "Serbian" },
  { code: "MA", name: "Morocco", nativeName: "المغرب", lang: "ar", langName: "Arabic" },
  { code: "MZ", name: "Mozambique", nativeName: "Moçambique", lang: "pt", langName: "Portuguese" },
  { code: "MM", name: "Myanmar", nativeName: "မြန်မာ", lang: "my", langName: "Burmese" },
  { code: "NA", name: "Namibia", nativeName: "Namibia", lang: "en", langName: "English" },
  { code: "NR", name: "Nauru", nativeName: "Nauru", lang: "en", langName: "English" },
  { code: "NP", name: "Nepal", nativeName: "नेपाल", lang: "ne", langName: "Nepali" },
  { code: "NL", name: "Netherlands", nativeName: "Nederland", lang: "nl", langName: "Dutch" },
  { code: "NZ", name: "New Zealand", nativeName: "New Zealand", lang: "en", langName: "English" },
  { code: "NI", name: "Nicaragua", nativeName: "Nicaragua", lang: "es", langName: "Spanish" },
  { code: "NE", name: "Niger", nativeName: "Niger", lang: "fr", langName: "French" },
  { code: "NG", name: "Nigeria", nativeName: "Nigeria", lang: "en", langName: "English" },
  { code: "MK", name: "North Macedonia", nativeName: "Северна Македонија", lang: "mk", langName: "Macedonian" },
  { code: "NO", name: "Norway", nativeName: "Norge", lang: "no", langName: "Norwegian" },
  { code: "OM", name: "Oman", nativeName: "عُمان", lang: "ar", langName: "Arabic" },
  { code: "PK", name: "Pakistan", nativeName: "پاکستان", lang: "ur", langName: "Urdu" },
  { code: "PW", name: "Palau", nativeName: "Palau", lang: "en", langName: "English" },
  { code: "PS", name: "Palestine", nativeName: "فلسطين", lang: "ar", langName: "Arabic" },
  { code: "PA", name: "Panama", nativeName: "Panamá", lang: "es", langName: "Spanish" },
  { code: "PG", name: "Papua New Guinea", nativeName: "Papua New Guinea", lang: "en", langName: "English" },
  { code: "PY", name: "Paraguay", nativeName: "Paraguay", lang: "es", langName: "Spanish" },
  { code: "PE", name: "Peru", nativeName: "Perú", lang: "es", langName: "Spanish" },
  { code: "PH", name: "Philippines", nativeName: "Pilipinas", lang: "en", langName: "English" },
  { code: "PL", name: "Poland", nativeName: "Polska", lang: "pl", langName: "Polish" },
  { code: "PT", name: "Portugal", nativeName: "Portugal", lang: "pt", langName: "Portuguese" },
  { code: "QA", name: "Qatar", nativeName: "قطر", lang: "ar", langName: "Arabic" },
  { code: "RO", name: "Romania", nativeName: "România", lang: "ro", langName: "Romanian" },
  { code: "RU", name: "Russia", nativeName: "Россия", lang: "ru", langName: "Russian" },
  { code: "RW", name: "Rwanda", nativeName: "Rwanda", lang: "rw", langName: "Kinyarwanda" },
  { code: "KN", name: "Saint Kitts and Nevis", nativeName: "Saint Kitts and Nevis", lang: "en", langName: "English" },
  { code: "LC", name: "Saint Lucia", nativeName: "Saint Lucia", lang: "en", langName: "English" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nativeName: "Saint Vincent and the Grenadines", lang: "en", langName: "English" },
  { code: "WS", name: "Samoa", nativeName: "Sāmoa", lang: "sm", langName: "Samoan" },
  { code: "SM", name: "San Marino", nativeName: "San Marino", lang: "it", langName: "Italian" },
  { code: "ST", name: "São Tomé and Príncipe", nativeName: "São Tomé e Príncipe", lang: "pt", langName: "Portuguese" },
  { code: "SA", name: "Saudi Arabia", nativeName: "السعودية", lang: "ar", langName: "Arabic" },
  { code: "SN", name: "Senegal", nativeName: "Sénégal", lang: "fr", langName: "French" },
  { code: "RS", name: "Serbia", nativeName: "Србија", lang: "sr", langName: "Serbian" },
  { code: "SC", name: "Seychelles", nativeName: "Seychelles", lang: "en", langName: "English" },
  { code: "SL", name: "Sierra Leone", nativeName: "Sierra Leone", lang: "en", langName: "English" },
  { code: "SG", name: "Singapore", nativeName: "Singapore", lang: "en", langName: "English" },
  { code: "SK", name: "Slovakia", nativeName: "Slovensko", lang: "sk", langName: "Slovak" },
  { code: "SI", name: "Slovenia", nativeName: "Slovenija", lang: "sl", langName: "Slovenian" },
  { code: "SB", name: "Solomon Islands", nativeName: "Solomon Islands", lang: "en", langName: "English" },
  { code: "SO", name: "Somalia", nativeName: "Soomaaliya", lang: "so", langName: "Somali" },
  { code: "ZA", name: "South Africa", nativeName: "South Africa", lang: "en", langName: "English" },
  { code: "SS", name: "South Sudan", nativeName: "South Sudan", lang: "en", langName: "English" },
  { code: "ES", name: "Spain", nativeName: "España", lang: "es", langName: "Spanish" },
  { code: "LK", name: "Sri Lanka", nativeName: "ශ්‍රී ලංකා", lang: "si", langName: "Sinhala" },
  { code: "SD", name: "Sudan", nativeName: "السودان", lang: "ar", langName: "Arabic" },
  { code: "SR", name: "Suriname", nativeName: "Suriname", lang: "nl", langName: "Dutch" },
  { code: "SE", name: "Sweden", nativeName: "Sverige", lang: "sv", langName: "Swedish" },
  { code: "CH", name: "Switzerland", nativeName: "Schweiz", lang: "de", langName: "German" },
  { code: "SY", name: "Syria", nativeName: "سوريا", lang: "ar", langName: "Arabic" },
  { code: "TW", name: "Taiwan", nativeName: "臺灣", lang: "zh", langName: "Chinese" },
  { code: "TJ", name: "Tajikistan", nativeName: "Тоҷикистон", lang: "tg", langName: "Tajik" },
  { code: "TZ", name: "Tanzania", nativeName: "Tanzania", lang: "sw", langName: "Swahili" },
  { code: "TH", name: "Thailand", nativeName: "ประเทศไทย", lang: "th", langName: "Thai" },
  { code: "TL", name: "Timor-Leste", nativeName: "Timor-Leste", lang: "pt", langName: "Portuguese" },
  { code: "TG", name: "Togo", nativeName: "Togo", lang: "fr", langName: "French" },
  { code: "TO", name: "Tonga", nativeName: "Tonga", lang: "en", langName: "English" },
  { code: "TT", name: "Trinidad and Tobago", nativeName: "Trinidad and Tobago", lang: "en", langName: "English" },
  { code: "TN", name: "Tunisia", nativeName: "تونس", lang: "ar", langName: "Arabic" },
  { code: "TR", name: "Turkey", nativeName: "Türkiye", lang: "tr", langName: "Turkish" },
  { code: "TM", name: "Turkmenistan", nativeName: "Türkmenistan", lang: "tk", langName: "Turkmen" },
  { code: "TV", name: "Tuvalu", nativeName: "Tuvalu", lang: "en", langName: "English" },
  { code: "UG", name: "Uganda", nativeName: "Uganda", lang: "en", langName: "English" },
  { code: "UA", name: "Ukraine", nativeName: "Україна", lang: "uk", langName: "Ukrainian" },
  { code: "AE", name: "United Arab Emirates", nativeName: "الإمارات", lang: "ar", langName: "Arabic" },
  { code: "GB", name: "United Kingdom", nativeName: "United Kingdom", lang: "en", langName: "English" },
  { code: "US", name: "United States", nativeName: "United States", lang: "en", langName: "English" },
  { code: "UY", name: "Uruguay", nativeName: "Uruguay", lang: "es", langName: "Spanish" },
  { code: "UZ", name: "Uzbekistan", nativeName: "Oʻzbekiston", lang: "uz", langName: "Uzbek" },
  { code: "VU", name: "Vanuatu", nativeName: "Vanuatu", lang: "en", langName: "English" },
  { code: "VA", name: "Vatican City", nativeName: "Città del Vaticano", lang: "it", langName: "Italian" },
  { code: "VE", name: "Venezuela", nativeName: "Venezuela", lang: "es", langName: "Spanish" },
  { code: "VN", name: "Vietnam", nativeName: "Việt Nam", lang: "vi", langName: "Vietnamese" },
  { code: "YE", name: "Yemen", nativeName: "اليمن", lang: "ar", langName: "Arabic" },
  { code: "ZM", name: "Zambia", nativeName: "Zambia", lang: "en", langName: "English" },
  { code: "ZW", name: "Zimbabwe", nativeName: "Zimbabwe", lang: "en", langName: "English" },
];

export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function getCountries(codes: string[]): Country[] {
  return codes.map((code) => getCountry(code)).filter(Boolean) as Country[];
}

export function countryFlag(code: string): string {
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join("");
}
